192.168.31.133:
  port: 22
  username: mysql
  # echo -n 'mysql$123' | base64
  # echo -n 'bXlzcWwkMTIz' | base64 -d
  password: bXlzcWwkMTIz
  tags:
    mysql: master
192.168.31.134:
  port: 22
  username: mysql
  # echo -n 'mysql$123' | base64
  # echo -n 'bXlzcWwkMTIz' | base64 -d
  password: bXlzcWwkMTIz
  tags:
    mysql: master
192.[22:26].[95:99].[95:99]:
  port: 22
  username: mysql
  # echo -n 'mysql$123' | base64
  # echo -n 'bXlzcWwkMTIz' | base64 -d
  password: bXlzcWwkMTIz
  tags:
    mysql: master